version: "3.9"

services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: banco_sangue
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/banco_sangue
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    volumes:
      - ./logs:/logs
volumes:
  db-data: